<?php

namespace Wtf\Core\Responses;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-08 at 14:31:43.
 */
class ErrorTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Error
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Error;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Wtf\Core\Responses\Error::configure
	 * @todo   Implement testConfigure().
	 */
	public function testConfigure() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\Responses\Error::config
	 * @todo   Implement testConfig().
	 */
	public function testConfig() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
