<?php

namespace Wtf\Traits;

class CreatorMock implements \Wtf\Interfaces\Creator {

	use Creator;

	public $arguments = null;

	function __construct() {
		$this->arguments = func_get_args();
	}

}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-10 at 16:38:04.
 */
class CreatorTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Creator
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Wtf\Traits\Creator::_
	 */
	public function test_() {
		$obj = CreatorMock::_();

		$this->assertInstanceOf(CreatorMock::class, $obj);
		$this->assertEmpty($obj->arguments);

		$obj = CreatorMock::_(1, true, 'string');
		$this->assertEquals([1, true, 'string'], $obj->arguments);
	}

}
