<?php

namespace Wtf\Traits;

class NamedMock implements \Wtf\Interfaces\Named {

	use Named;
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-13 at 13:47:09.
 */
class NamedTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Named
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Wtf\Traits\Named::name
	 */
	public function testNameString() {
		$obj = new NamedMock();

		$this->assertEquals('nammed', $obj->name('nammed'));
		$this->assertEquals('nammed', $obj->name());
	}

	/**
	 * @covers Wtf\Traits\Named::name
	 */
	public function testNameAuto() {
		$obj = new NamedMock();

		$this->assertInternalType('string', $name = $obj->name());
		$this->assertEquals($name, $obj->name());
	}

}
