<?php

namespace Wtf\Core\Responses;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-16 at 16:32:44.
 */
class XmlTest extends \PHPUnit_Framework_TestCase {

	protected $fixture = [
		'foo' => 'Foo',
		'bar' => [
			1, 2, 3, 4, 5
		],
	];

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Wtf\Core\Responses\Xml::__construct
	 */
	public function test__construct() {
		$obj = new Xml($this->fixture);
		$this->assertAttributeEquals($this->fixture, '_data', $obj);
		return $obj;
	}
	/**
	 * @depends test__construct
	 * @covers Wtf\Core\Responses\Xml::__toString
	 */
	public function test__toString($obj) {
		$xml = \Wtf\Helper\Complex::arr2xml($this->fixture)->asXML();
		$this->assertEquals($xml, (string) $obj);
		$this->assertEquals([], headers_list());
		$this->assertAttributeEquals([
				'Content-Type' => 'text/xml',
				'Content-Length' => strlen($xml)
			], '_headers', $obj);
	}

	/**
	 * @depends test__construct
	 * @covers Wtf\Core\Responses\Xml::clear
	 */
	public function testClear($obj) {
		$this->assertSame($obj, $obj->clear());
		$this->assertAttributeEquals([], '_data', $obj);
	}

}
