<?php namespace Wtf\Core\Entities;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-09 at 09:30:48.
 */
class CssTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Css
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Css;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Wtf\Core\Entities\Css::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Core\Entities\Css::attrsLines
     * @todo   Implement testAttrsLines().
     */
    public function testAttrsLines()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
