<?php

namespace Wtf\Helper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-27 at 10:09:58.
 */
class CommonTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Common
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Wtf\Helper\Common::parsePhp
	 * @todo   Implement testParsePhp().
	 */
	public function testParsePhp() {
		$phpret = <<<EOT
<?php
	return 'some text';
?>

EOT;

		$phpstr = <<<EOT
<?php
	'some text';
?>

EOT;

		$phparr = <<<EOT
<?php
	return ['some text'];
?>

EOT;

		$this->assertEquals('some text', Common::parsePhp($phpret));
		$this->assertNull(Common::parsePhp($phpstr));
		$this->assertEquals(['some text'], Common::parsePhp($phparr));
	}

}
