<?php

namespace Wtf\Helper;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-23 at 16:06:12.
 */
class ComplexTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Complex
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Complex;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Wtf\Helper\Complex::except
     * @todo   Implement testExcept().
     */
    public function testExcept() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Helper\Complex::only
     * @todo   Implement testOnly().
     */
    public function testOnly() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Helper\Complex::obj2arr
     * @todo   Implement testObj2arr().
     */
    public function testObj2arr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Helper\Complex::arr2obj
     * @todo   Implement testArr2obj().
     */
    public function testArr2obj() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Helper\Complex::arr2ini
     * @todo   Implement testArr2ini().
     */
    public function testArr2ini() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Helper\Complex::ini2arr
     * @todo   Implement testIni2arr().
     */
    public function testIni2arr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Helper\Complex::get
     * @todo   Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Helper\Complex::eliminate
     * @todo   Implement testEliminate().
     */
    public function testEliminate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Helper\Complex::arr2attr
     * @todo   Implement testArr2attr().
     */
    public function testArr2attr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Helper\Complex::attr2arr
     * @todo   Implement testAttr2arr().
     */
    public function testAttr2arr() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
