<?php

namespace Wtf\Core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-27 at 10:15:58.
 */
class CompilerTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Compiler
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Compiler;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Wtf\Core\Compiler::compile
	 * @todo   Implement testCompile().
	 */
	public function testCompile() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\Compiler::factory
	 * @todo   Implement testFactory().
	 */
	public function testFactory() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\Compiler::make
	 * @todo   Implement testMake().
	 */
	public function testMake() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\Compiler::camelCase
	 * @todo   Implement testCamelCase().
	 */
	public function testCamelCase() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\Compiler::snakeCase
	 * @todo   Implement testSnakeCase().
	 */
	public function testSnakeCase() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\Compiler::plural
	 * @todo   Implement testPlural().
	 */
	public function testPlural() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\Compiler::__callStatic
	 * @todo   Implement test__callStatic().
	 */
	public function test__callStatic() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
