<?php

namespace Wtf\Core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-27 at 10:15:57.
 */
class DatasetTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Dataset
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Dataset;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Wtf\Core\Dataset::execute
	 * @todo   Implement testExecute().
	 */
	public function testExecute() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\Dataset::instance
	 * @todo   Implement testInstance().
	 */
	public function testInstance() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\Dataset::configure
	 * @todo   Implement testConfigure().
	 */
	public function testConfigure() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\Dataset::config
	 * @todo   Implement testConfig().
	 */
	public function testConfig() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\Dataset::observe
	 * @todo   Implement testObserve().
	 */
	public function testObserve() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
