<?php

namespace Wtf\Core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-27 at 10:15:52.
 */
class I18nTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var I18n
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new I18n;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Wtf\Core\I18n::init
	 * @todo   Implement testInit().
	 */
	public function testInit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\I18n::__callStatic
	 * @todo   Implement test__callStatic().
	 */
	public function test__callStatic() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\I18n::get
	 * @todo   Implement testGet().
	 */
	public function testGet() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\I18n::find
	 * @todo   Implement testFind().
	 */
	public function testFind() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\I18n::choose
	 * @todo   Implement testChoose().
	 */
	public function testChoose() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\I18n::substitute
	 * @todo   Implement testSubstitute().
	 */
	public function testSubstitute() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\I18n::configure
	 * @todo   Implement testConfigure().
	 */
	public function testConfigure() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\I18n::config
	 * @todo   Implement testConfig().
	 */
	public function testConfig() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
