<?php namespace Wtf\Core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-09 at 09:30:51.
 */
class RuleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Rule
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Rule;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Wtf\Core\Rule::any
     * @todo   Implement testAny().
     */
    public function testAny()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Core\Rule::__callStatic
     * @todo   Implement test__callStatic().
     */
    public function test__callStatic()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Core\Rule::bootstrap
     * @todo   Implement testBootstrap().
     */
    public function testBootstrap()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Wtf\Core\Rule::build
     * @todo   Implement testBuild().
     */
    public function testBuild()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
