<?php

namespace Wtf\Core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-27 at 10:15:58.
 */
class ServerTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Server
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = Server::singleton();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Wtf\Core\Server::get
	 */
	public function testContainer() {
		$this->assertEquals($_SERVER['SCRIPT_FILENAME'],$this->object->get('Script_FileName'));
	}
}
