<?php

namespace Wtf\Core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-17 at 13:15:54.
 */
class TrashbinTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Trashbin
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = Trashbin::singleton();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Wtf\Core\Trashbin::singleton
	 */
	public function testSingleton() {
		$object = Trashbin::singleton();
		$this->assertSame($this->object,$object);
		
		return $object;
	}

	/**
	 * @depends testSingleton
	 * @covers Wtf\Core\Trashbin::__invoke
	 */
	public function test__invoke($object) {
		$this->assertEquals([],$object());
		$this->assertEquals(['foo'],$object('foo'));
		$this->assertEquals(['foo','bar','baz'],$object(['bar','baz']));
	}

}
