<?php

namespace Wtf\Core;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 17:15:50.
 */
class EventManagerTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var EventManager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Wtf\Core\EventManager::observe
	 * @todo   Implement testObserve().
	 */
	public function testObserve() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\EventManager::add
	 * @todo   Implement testAdd().
	 */
	public function testAdd() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\EventManager::remove
	 * @todo   Implement testRemove().
	 */
	public function testRemove() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\EventManager::subscribe
	 * @todo   Implement testSubscribe().
	 */
	public function testSubscribe() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\EventManager::unsubscribe
	 * @todo   Implement testUnsubscribe().
	 */
	public function testUnsubscribe() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\EventManager::register
	 * @todo   Implement testRegister().
	 */
	public function testRegister() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\EventManager::unregister
	 * @todo   Implement testUnregister().
	 */
	public function testUnregister() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Wtf\Core\EventManager::fire
	 * @todo   Implement testFire().
	 */
	public function testFire() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}
